// @bloopnet/libbloop
//
// TypeScript wrapper around the bloop-wasm WASM package.
// Build the WASM first: npm run build:wasm

// ── Types ─────────────────────────────────────────────────────────────────────

export interface EncodedBloop {
  readonly bytes: Uint8Array;
  readonly symbolCount: number;
}

export interface ValidationIssue {
  readonly kind:
    | "UnsupportedCharacter"
    | "DanglingEscape"
    | "IncompleteEscape"
    | "UnbalancedPipe"
    | "UnknownExtensionBank"
    | "MessageTooLong";
  readonly position: number | null;
  readonly message: string;
}

export interface ValidationReport {
  readonly ok: boolean;
  readonly issues: ValidationIssue[];
}

export interface InspectionReport {
  readonly text: string;
  readonly symbols: number;
  readonly bits: number;
  readonly payloadBytes: number;
  readonly valid: boolean;
  readonly issues: ValidationIssue[];
  readonly sizeClass: "pulse" | "bloop" | "longbloop" | "flood" | "too long";
  readonly loraPolite: boolean;
}

// ── WASM module import ────────────────────────────────────────────────────────
//
// The wasm/ directory is generated by `npm run build:wasm`.
// It will contain bloop_wasm.js, bloop_wasm_bg.wasm, and bloop_wasm.d.ts.

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — populated after `npm run build:wasm`
import * as wasm from "../wasm/bloop_wasm.js";

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Encode a Bloop text string to packed 5-bit bytes.
 *
 * Throws if the input contains unsupported characters (uppercase, digits,
 * unrecognised punctuation). Use `validateText` first to check.
 */
export function encodeText(input: string): EncodedBloop {
  const enc = wasm.encodeText(input);
  return { bytes: enc.bytes, symbolCount: enc.symbolCount };
}

/**
 * Decode packed bytes back to text.
 * `symbolCount` must match the value returned by `encodeText`.
 */
export function decodeText(bytes: Uint8Array, symbolCount: number): string {
  return wasm.decodeText(bytes, symbolCount);
}

/**
 * Validate a Bloop text string.
 * Returns a report with `ok: true` and an empty issue list if the input is clean.
 */
export function validateText(input: string): ValidationReport {
  return wasm.validateText(input) as ValidationReport;
}

/**
 * Inspect a Bloop text string: symbol count, bit count, size class, and
 * full validation report.
 */
export function inspectText(input: string): InspectionReport {
  const raw = wasm.inspectText(input);
  return {
    text: raw.text,
    symbols: raw.symbols,
    bits: raw.bits,
    payloadBytes: raw.payloadBytes,
    valid: raw.valid,
    issues: raw.issues,
    sizeClass: raw.sizeClass,
    loraPolite: raw.loraPolite,
  };
}
